POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Sravan Gunaganti",
  "password": "Sravan@376",
  "gender": "male",
  "location": "Detroit"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "sravan_gunaganti",
  "password": "Sravan@376"
}
###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
  "username": "sravan_gunaganti",
  "oldPassword": "Sravan@376",
  "newPassword": "Sravan@376"
}
